# Generated by Django 5.0.6 on 2024-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online Payment', 'Online Payment'), ('Bank Transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
